---
version: '3.4'
services:
  operator:
    command:
      - ansible-runner
      - run
      - -vvv
      - /runner
    depends_on:
      - svn
    environment:
      SVN_REPOSITORY_URL: svn://svn/project-in-svn

  workspace:
    environment:
      SVN_USER_NAME: ${SVN_USER_NAME:?err}
      SVN_USER_PASS: ${SVN_USER_PASSWORD:?err}
    volumes:
      - svn-repository:/var/opt/svn

  svn:
    container_name: svn
    image: garethflowers/svn-server
    ports:
      - 3690:3690
    volumes:
      - svn-repository:/var/opt/svn
volumes:
  svn-repository:
  