---
version: '3.4'
services:
  operator:
    command:
      - /bin/bash
    depends_on:
      - svn
    environment:
      HOME: /root
      SVN_REPOSITORY_URL: svn://svn/project-in-svn
    image: futureys/ansible-runner-python3:20191127153000
    tty: true
    volumes:
      - ./pytest:/root/pytest
      # Because /runner is home directory,
      # to escape some trouble, mount each directories individually
      - ./runner/env:/runner/env
      - ./runner/inventory:/runner/inventory
      - ./runner/project:/runner/project
    working_dir: /root/pytest

  workspace:
    environment:
      SVN_USER_NAME: ${SVN_USER_NAME:?err}
      SVN_USER_PASS: ${SVN_USER_PASSWORD:?err}
    volumes:
      - svn-repository:/var/opt/svn

  svn:
    container_name: svn
    image: garethflowers/svn-server
    ports:
      - 3690:3690
    volumes:
      - svn-repository:/var/opt/svn
volumes:
  svn-repository:
