---
version: '3.4'
services:
  sut:
    build:
      context: .
    depends_on:
      - svn
    environment:
      GIT_REPOSITORY_URL: https://github.com/yukihiko-shinoda/staticpress.git
      SVN_REPOSITORY_URL: svn://svn/project-in-svn
      SVN_USER_NAME: svn_user_name
      SVN_USER_PASSWORD: p@ssW0rd
    volumes:
      - ./pytest:/root/pytest
      - svn-repository:/var/opt/svn

  svn:
    container_name: svn
    image: garethflowers/svn-server
    volumes:
      - svn-repository:/var/opt/svn
volumes:
  svn-repository:
