---
version: '3.4'
services:
  operator:
    command:
      - /bin/bash
    depends_on:
      - svn
    environment:
      HOME: /root
      SVN_REPOSITORY_URL: svn://svn/project-in-svn
    image: futureys/ansible-runner-python3:20191127153000
    tty: true
    volumes:
      - ./pytest:/root/pytest
      - ./runner/env:/runner/env
      - ./runner/inventory:/runner/inventory
      - ./runner/project:/runner/project
    working_dir: /root/pytest

  svn:
    container_name: svn
    environment:
      USER_1_NAME: ${SVN_USER_NAME:?err}
      USER_1_PASS: ${SVN_USER_PASSWORD:?err}
    image: futureys/svn-repository
    ports:
      - 3690:3690
