---
version: '3.8'
services:
  deploy:
    command:
      - ansible-runner
      - run
      - -vvv
      - /runner
    depends_on:
      - svn
    environment:
      SVN_REPOSITORY_URL: svn://svn/project-in-svn
      SVN_USER_NAME: ${SVN_USER_NAME:?err}
      SVN_USER_PASSWORD: ${SVN_USER_PASSWORD:?err}
    volumes:
      - svn-repository:/var/opt/svn

  svn:
    image: garethflowers/svn-server
    ports:
      - 3690:3690
    volumes:
      - svn-repository:/var/opt/svn
volumes:
  svn-repository:
  