---
version: '3.4'
services:
  operator:
    container_name: operator
    environment:
      GIT_REPOSITORY_URL: ${GIT_REPOSITORY_URL}
      GIT_PATH_CHECKED_OUT: ${GIT_PATH_CHECKED_OUT}
      SVN_REPOSITORY_URL: ${SVN_REPOSITORY_URL}
      SVN_USER_NAME: ${SVN_USER_NAME}
      SVN_USER_PASSWORD: ${SVN_USER_PASSWORD}
      DEPLOY_VERSION: ${DEPLOY_VERSION}
      SHOW_ALL_LOG: ${SHOW_ALL_LOG}
    image: futureys/deploy-wordpress-plugin
