---
version: '3.4'
services:
  operator:
    container_name: operator
    depends_on:
      - workspace
    environment:
      ANSIBLE_SSH_HOST: workspace
      ANSIBLE_SSH_USER: root
      ANSIBLE_SSH_PASS: p@ssW0rd
      # ↓ Specification of Python on Alpine official container
      # ↓ @see https://hub.docker.com/_/python
      ANSIBLE_PYTHON_INTERPRETER: /usr/local/bin/python
      GIT_REPOSITORY_URL: ${GIT_REPOSITORY_URL}
      SVN_REPOSITORY_URL: ${SVN_REPOSITORY_URL}
      SVN_USER_NAME: ${SVN_USER_NAME}
      SVN_USER_PASSWORD: ${SVN_USER_PASSWORD}
      DEPLOY_VERSION: ${DEPLOY_VERSION}
    image: futureys/deploy-wordpress-plugin

  workspace:
    container_name: workspace
    environment:
      SSH_PASSWORD: p@ssW0rd
    image: futureys/ansible-workspace-deploy-wordpress-plugin:20200205110500
