---
- name: Ensure that only either of git_repository_url or git_path_checked_out is defined
  fail:
    msg: |
      only either of git_repository_url or git_path_checked_out can be defined.
      git_repository_url = {{ git_repository_url }}
      git_path_checked_out = {{ git_path_checked_out }}
  when: git_repository_url != '' and git_path_checked_out != '' or git_repository_url == '' and git_path_checked_out == ''

- name:
  include_tasks: check_out_git_repository.yml
  when: git_repository_url != ''

- name:
  include_tasks: validate_git_repository_checked_out.yml
  when: git_path_checked_out != ''

- name: Validate deploy version by Git
  include_tasks: validate_deploy_version_by_git.yml

- name: Grep stable tag
  include_tasks: grep_plugin_data.yml
  vars:
    path_to_file: '{{ path_checkout_git }}/readme.txt'
    regex: '[ \t\/*#@]*Stable\stag:.*$'
    arrow_no_lines: yes

- name: Define stable tag
  set_fact:
    stable_tag: '{{ result_grep.stdout if (result_grep.stdout_lines | length) == 1 else trunk }}'

- name: Checkout svn repository
  subversion:
    repo: '{{ svn_repository_url }}'
    dest: '{{ workspace }}{{ directory_name_checkout_subversion }}'
    force: yes

- name: Validate deploy version by SVN
  include_tasks: validate_deploy_version_by_svn.yml

- name: Validate stable tag
  include_tasks: validate_stable_tag.yml
  when: stable_tag != 'trunk'
