on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@v2
      - id: buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - id: extract-tag
        run: echo ::set-output name=DOCKER_TAG::$(echo ${GITHUB_REF#refs/tags/v})
      - uses: docker/build-push-action@v3
        with:
          push: true
          target: production
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/deploy-wordpress-plugin:latest,${{ secrets.DOCKER_HUB_USERNAME }}/deploy-wordpress-plugin:${{ steps.extract-tag.outputs.DOCKER_TAG }}
          builder: ${{ steps.buildx.outputs.name }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/deploy-wordpress-plugin:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_HUB_USERNAME }}/deploy-wordpress-plugin:buildcache,mode=max
